site_name: Cross Renamer Tool
use_directory_urls: true
site_url: https://lucileleboullec.github.io/CrossRenamerTool/

docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - search
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.instant
    - navigation.hidden
    - navigation.tabs
    - toc.follow
    - content.code.copy
    - content.tabs.link
    - search.highlight
    - search.share

  font:
    text: Roboto
    code: Roboto Mono
  

  palette:
    # Palette toggle for light mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for dark mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

plugins:
  - search
  - mermaid2
  - mkdocstrings:
     default_handler: python
     handlers:
       python:
         paths: [src]
         options:
           docstring_style: google
           heading_level: 3
           show_source: true
           group_by_category: true
           show_category_heading: true
           show_root_toc_entry: false
           merge_init_into_class: true
markdown_extensions:
  # Python Markdown
  - toc:
      permalink: true
  - attr_list: {}
  # Python Markdown Extensions
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home : index.md
  - Installation: installation.md
  - User Manual:
    - Overview: user_manual/index.md
    - Tutorials:
      - Overview: user_manual/tutorials/index.md
    - How to Guides:
      - Overview: user_manual/how-to-guides/index.md
      - Create Shelf Button : user_manual/how-to-guides/guides/create_shelf_button.md
    - References:
      - Overview: user_manual/references/index.md
    - Explanations:
      - Explanations: user_manual/explanations/index.md
  - Developer Docs:
    - Overview: developer_docs/index.md
    - Tutorials:
      - Overview: developer_docs/tutorials/index.md
    - How to Guides:
      - Overview: developer_docs/how-to-guides/index.md
    - References:
      - Overview: developer_docs/references/index.md
      - Architecture: developer_docs/references/architecture.md
    - Explanations:
      - Explanations: developer_docs/explanations/index.md

  - API:
    - Overview: API/index.md
    - Controller : API/controller/index.md
    - Model : 
      - Overview: API/model/index.md
      - Blender API: API/model/blender_api.md
      - Maya API: API/model/maya_api.md
    - View : 
      - Overview: API/view/index.md
      - Blender: API/view/blender/index.md
      - Maya:
        - Overview: API/view/maya/index.md
        - Main Window: API/view/maya/main_window.md
        - Widgets: 
          - Overview: API/view/maya/widgets/index.md
          - About Dialog: API/view/maya/widgets/about_dialog.md
          - Case Widget: API/view/maya/widgets/case_widget.md
          - Insert Remove Widget: API/view/maya/widgets/insert_remove_widget.md
          - Prefix Suffix Widget: API/view/maya/widgets/prefix_suffix_widget.md
          - Preset Combobox: API/view/maya/widgets/preset_combobox.md
          - Preset Dialog: API/view/maya/widgets/preset_dialog.md
          - Rename Widget: API/view/maya/widgets/rename_widget.md
          - Search Replace Widget: API/view/maya/widgets/search_replace_widget.md
          - Selection Mode Widget: API/view/maya/widgets/selection_mode_widget.md
          - Utils Widget: API/view/maya/widgets/utils_widget.md
    - Core : 
      - Overview: API/core/index.md
      - Constants : API/core/constants.md
      - Presets : API/core/presets.md
      - Renamer : API/core/renamer.md