name: Main Workflow

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    uses: ./.github/workflows/linter.yml
  docs:
    uses: ./.github/workflows/mkdocs.yml
