name: Main Workflow

on:
  push:
    branches:
      - main
      - develop
      - cicd

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    uses: ./.github/workflows/linter.yml
  tests:
    needs: lint
    uses: ./.github/workflows/tests.yml
  docs:
    needs: tests
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/mkdocs.yml
