name: Deploy Docs Dev

on:
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    name: Deploy docs (develop)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy docs dev
        run: mkdocs gh-deploy --force --remote-branch gh-pages-dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}